spring.application.name: metadata-refactor
vcb.batch.input.location: D:\log-file\
server:
  port: 8081
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCL
    username: system
    password: 123456789
    driver-class-name: oracle.jdbc.OracleDriver
  servlet:  
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  jpa:
    properties:
      hibernate:
        default_schema: SYSTEM
        format_sql: true
    show-sql: true
  batch:
    jdbc:
      initialize-schema: always