spring.application.name: metadata-refactor
server:
  port: 8081
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCL
    username: system
    password: 123456789
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    properties:
      hibernate:
        default_schema: SYSTEM